DapperGraphs/Models/EnergyUsageData.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DapperGraphs.Models
{
    public class EnergyUsageData
    {
        [Key]
        public Guid EnergyUsageDataId { get; set; }

        [Required]
        [Display(Name = "Ano")]
        public short Year { get; set; }
        //Energy use (kg of oil equivalent per capita)
        [Display(Name = "Valor (Kg de óleo equivalente per capita)")]
        public float Value { get; set; }

        public Guid CountryId { get; set; }
        public virtual Country Country { get; set; }
    }
}

DapperGraphs/Controllers/EnergyUsageDatasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DapperGraphs.Models;
using Dapper;
using DapperGraphs.ViewModels;
using Newtonsoft.Json;
using System.Data.SqlClient;

namespace DapperGraphs.Controllers
{
    [Authorize]
    public class EnergyUsageDatasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        /// <summary>
        /// GET: gera relatório básico de uso de energia per capita anul de cada páis (todo período)
        /// </summary>
        /// <returns>Retorna uma lista de <see cref="EnergyUsageData"/> para exibição em listagem.</returns>
        public async Task<ActionResult> Index()
        {
            string sql = @"select e.EnergyUsageDataId, e.CountryId, e.Year, e.Value, c.CountryId, c.Name
                        from EnergyUsageDatas e
                        join countries c on c.CountryId = e.CountryId
                        order by c.Name";

            using (db)
            {
                var energyUsageDatas = await db.Database.Connection.QueryAsync<EnergyUsageData, Country, EnergyUsageData>(sql,
                    (energyUsageData, country) =>
                    {
                        energyUsageData.Country = country;
                        return energyUsageData;
                    },
                    splitOn: "Value,CountryId"
                );

                return View(energyUsageDatas);
            }
        }

        /// <summary>
        /// GET: Action para específicar parâmetros de consulta de Relatório análitico por período de ano de determinado país.
        /// Ao inicilizar a lista de países é carregada do BD para seleção do usuário.
        /// </summary>
        /// <returns>View de RelatorioAnalitico com os campos a serem parametrizados pelo usuários.</returns>
        public ActionResult RelatorioAnalitico()
        {
            using (db)
            {
                var paises = db.Countries.OrderBy(c => c.Name).ToList();
                List<SelectListItem> listItemPaises = paises.Select(x => new SelectListItem() { Value = x.CountryId.ToString(), Text = x.Name.ToString() }).ToList();
                listItemPaises.Insert(0, new SelectListItem { Value = string.Empty, Text = "Escolher..." });
                ViewBag.Paises = listItemPaises;
                return View();
            }
        }

        /// <summary>
        /// GET: gerar o relatório parametrizado em <see cref="RelatorioAnalitico"/>.
        /// </summary>
        /// <param name="anoInicial">Ano inicial do período a ser consultado.</param>
        /// <param name="anoFinal">Ano final do período a ser consultado.</param>
        /// <param name="paises">Id (Guid) do país a ser consultado.</param>
        /// <returns>Retorna para a view GerarRelatorioAnalitico uma lista de <see cref="EnergyUsageData"/> para geração do relatório.</returns>
        public async Task<ActionResult> GerarRelatorioAnalitico(short anoInicial, short anoFinal, Guid paises)
        {
            string sql = @"select e.EnergyUsageDataId, e.CountryId, e.Year, e.Value, c.CountryId, c.Name
                        from EnergyUsageDatas e
                        join countries c on c.CountryId = e.CountryId
                        where c.CountryId = @IdPais
                        and e.Year >= @IdAnoInicio and e.Year <= @IdAnoFim
                        and e.Value > 0
                        order by e.Year";

            using (db)
            {
                //Dapper:
                var energyUsageDatas = await db.Database.Connection.QueryAsync<EnergyUsageData, Country, EnergyUsageData>(sql,
                    (energyUsageData, country) =>
                    {
                        energyUsageData.Country = country;
                        return energyUsageData;
                    },
                    splitOn: "Value,CountryId",
                    param: new
                    {
                        IdPais = paises.ToString(),
                        IdAnoInicio = anoInicial,
                        IdAnoFim = anoFinal
                    }
                );

                return View(energyUsageDatas);
            }
        }

        /// <summary>
        /// View com campos para parametrizar relatório de métricas.
        /// </summary>
        /// <returns>Retorna a view com campos de parametrização do relatório.</returns>
        public ActionResult RelatorioAnaliticoMetricas()
        {
            return View();
        }

        /// <summary>
        /// Gerar relatório de métricas parametrizado em <see cref="RelatorioAnaliticoMetricas"/>.
        /// </summary>
        /// <param name="anoInicial">Ano inicial do período a ser consultado.</param>
        /// <param name="anoFinal">Ano final do período a ser consultado.</param>
        /// <returns></returns>
        public async Task<ActionResult> GerarRelatorioAnaliticoMetricas(short anoInicial, short anoFinal)
        {
            string sql = @"select c.Name as NomePais, AVG(e.Value) as media, STDEVP(e.Value) as DesvioPadrao,  MIN(e.Value) as Minimo, MAX(e.Value) as Maximo
                            from EnergyUsageDatas e
                            join countries c on c.CountryId = e.CountryId
                            where e.Year >= @IdAnoInicio and e.Year <= @IdAnoFim
                            and e.Value > 0
                            group by c.Name
                            order by c.Name";
            
            using (db)
            {
                var relatorioMetricas = await db.Database.Connection.QueryAsync<RelatorioMetricasViewModels>(sql,
                    param: new
                    {
                        IdAnoInicio = anoInicial,
                        IdAnoFim = anoFinal
                    }
                );

                return View(relatorioMetricas);
            }
        }

        /// <summary>
        /// Gerar gráfico de metricas com Média, Desvio Padrão, Mínimo e Máximo de 4 países aleatórios.
        /// Após carregar o gráfico com os países aleatórios o usuários pode configurar os filtros e período como preferir.
        /// </summary>
        /// <returns>Retorna a view com o gráfico com os países selecionados aleatóriamente.</returns>
        public ActionResult GerarGraficoMetricas()
        {
            MetricChartParameterViewModel metricChartData = new MetricChartParameterViewModel();
            metricChartData.AnoInicial = 1990;
            metricChartData.AnoFinal = 2005;

            using (db)
            {
                var paises = db.Countries.ToList();

                metricChartData.ListaPaises = paises.OrderBy(o => o.Name).Select(x =>
                    new SelectListItem()
                    {
                        Value = x.CountryId.ToString(),
                        Text = x.Name
                    });

                string sql = @"select TOP(4)
                            c.Name as NomePais, AVG(e.Value) as media, STDEVP(e.Value) as DesvioPadrao,  MIN(e.Value) as Minimo, MAX(e.Value) as Maximo
                            from EnergyUsageDatas e
                            join countries c on c.CountryId = e.CountryId
                            where e.Year >= @IdAnoInicio and e.Year <= @IdAnoFim
                            and c.CountryId in @listaIdPaises
                            and e.Value > 0
                            group by c.Name
                            order by NEWID()";

                ViewBag.StartChart = db.Database.Connection.Query<RelatorioMetricasViewModels>(sql,
                    param: new
                    {
                        IdAnoInicio = metricChartData.AnoInicial,
                        IdAnoFim = metricChartData.AnoFinal,
                        listaIdPaises = paises.Select(s => s.CountryId).ToArray()
                    }
                );

                return View(metricChartData);
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="anoInicial"></param>
        /// <param name="anoFinal"></param>
        /// <param name="listaIdPaises"></param>
        /// <returns></returns>
        /// <remarks>https://jsfiddle.net/Wurthmann/hfjutm57/10/</remarks>
        [HttpPost]
        public JsonResult GerarDadosGraficoMetricas(MetricChartParameterViewModel paramsMetricChart)
        {
            string sql = @"select c.Name as NomePais, AVG(e.Value) as media, STDEVP(e.Value) as DesvioPadrao,  MIN(e.Value) as Minimo, MAX(e.Value) as Maximo
                            from EnergyUsageDatas e
                            join countries c on c.CountryId = e.CountryId
                            where e.Year >= @IdAnoInicio and e.Year <= @IdAnoFim
                            and c.CountryId in @listaIdPaises
                            and e.Value > 0
                            group by c.Name
                            order by c.Name";

            using (db)
            {
                var relatorioMetricas = db.Database.Connection.Query<RelatorioMetricasViewModels>(sql,
                    param: new
                    {
                        IdAnoInicio = paramsMetricChart.AnoInicial,
                        IdAnoFim = paramsMetricChart.AnoFinal,
                        listaIdPaises = paramsMetricChart.ListaIdPaises
                    }
                );

                return Json(relatorioMetricas);
            }
        }

        /// <summary>
        /// Gráfico de colunas com o TOP 10 países com maior valor de energia per capita durante todo período.
        /// </summary>
        /// <returns>Retorna a view com uma gráfico de coluna populado por <see cref="GerarDadosRelatorioTop10"/></returns>
        public ActionResult GerarGraficoTop10()
        {
            return View();
        }

DapperGraphs/Views/EnergyUsageDatas/Create.cshtml
@model DapperGraphs.Models.EnergyUsageData

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>EnergyUsageData</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CountryId, "CountryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CountryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CountryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DapperGraphs/Views/EnergyUsageDatas/Delete.cshtml
@model DapperGraphs.Models.EnergyUsageData

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EnergyUsageData</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Country.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DapperGraphs/Views/EnergyUsageDatas/Details.cshtml
@model DapperGraphs.Models.EnergyUsageData

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>EnergyUsageData</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Country.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.EnergyUsageDataId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DapperGraphs/Views/EnergyUsageDatas/Edit.cshtml
@model DapperGraphs.Models.EnergyUsageData

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>EnergyUsageData</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.EnergyUsageDataId)

        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CountryId, "CountryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CountryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CountryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DapperGraphs/Views/EnergyUsageDatas/GerarGraficoLinhaTop10.cshtml
@{
    ViewBag.Title = "Relatório Gráfico de Linha";
}

<h2>Relatório Gráfico de Linha - Top 10 países</h2>

<div id="linechart_material"></div>

@section Scripts {
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $.ajax({
                type: 'POST',
                dataType: 'json',
                contentType: 'application/json',
                url: '@Url.Action("GerarDadosRelatorioLinhaTop10", "EnergyUsageDatas")',
                success: function (result) {
                    google.charts.load('current', { 'packages': ['line'] });
                    google.charts.setOnLoadCallback(function () {
                        drawLineChart(result);
                    });
                }
            });
        });

        function drawLineChart(result) {
            var data = new google.visualization.DataTable();

            var arrays = result.map(value => value.Countrys);

            data.addColumn('number', 'Ano');
            //Adiciona cada país nas colunas do gráfico
            var arrayLength = arrays[0].length;
            for (var i = 0; i < arrayLength; i++) {
                data.addColumn('number', arrays[0][i]);
            }

            //Montar array com valores por ano
            var dataLineChart = result[0].ListDataPerYear.map(dataPerYear => [dataPerYear.Year, ...dataPerYear.ListValues]);

            data.addRows(dataLineChart);

            var arrays = [
                result.map(value => value.Year),
            ];

            console.log(result);

            var options = {
                legend: {
                    position: 'top',
                    textStyle: {
                        color: '#999'
                    }
                },
                chart: {
                    title: 'Gráfico de uso de energia per capita',
                    subtitle: 'Valor (Kg de óleo equivalente per capita)'
                },
                width: 1200,
                height: 800
            };

            var chart = new google.charts.Line(document.getElementById('linechart_material'));

            chart.draw(data, google.charts.Line.convertOptions(options));
        }
    </script>
}

DapperGraphs/Views/EnergyUsageDatas/GerarGraficoMetricas.cshtml
@model DapperGraphs.ViewModels.MetricChartParameterViewModel
@{
    ViewBag.Title = "Gráfico Métricas";
}

<h2> </h2>
<button type="button" id="btnApplyChart" class="btn btn-primary col-md-3">Aplicar</button>
<div class="form-horizontal col-md-9">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.AnoInicial, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.AnoInicial, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AnoInicial, "", new { @class = "text-danger" })
        </div>
        @Html.LabelFor(model => model.AnoFinal, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.AnoFinal, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AnoFinal, "", new { @class = "text-danger" })
        </div>
    </div>
</div>

<div class="row">
    <div class="list-group col-md-3 scrollit">
        @foreach (SelectListItem item in Model.ListaPaises)
        {
            <span class="list-group-item"><input type="checkbox" name="ListaIdPaises" value="@item.Value" /> @item.Text</span>
        }
    </div>
    <div id="chartMetricas" class="col-md-9"></div>
</div>

@section Scripts {
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">

        $("#btnApplyChart").click(function () {
            loadChartData();
        });

        //Redesenhar o gráfico com os dados dos países selecionados
        function loadChartData() {
            var listaIdPaises = new Array();
            $("input[name='ListaIdPaises']:checked").each(function (i) {
                listaIdPaises.push($(this).val());
            });

            var requestData = {
                AnoInicial: $.trim($('#AnoInicial').val()),
                AnoFinal: $.trim($('#AnoFinal').val()),
                ListaIdPaises: listaIdPaises
            };

            $.ajax({
                type: 'POST',
                dataType: 'json',
                contentType: "application/json; charset=utf-8;",
                url: '@Url.Action("GerarDadosGraficoMetricas", "EnergyUsageDatas")',
                data: JSON.stringify(requestData),
                success: function (relatorioMetricas) {
                    if (relatorioMetricas) {
                        reloadChart(relatorioMetricas);
                    }
                },
                error: function () {
                    alert("Oops! Algo deu errado.");
                }
            });
        }
        
        //Desenha o gráfico com valores padrões ao carregar a página
        google.charts.load('current', { 'packages': ['bar'] });
        google.charts.setOnLoadCallback(drawChart);

        function drawChart() {
            var dataChartJson = @Html.Raw(Json.Encode(ViewBag.StartChart));

            var dataAsArray = dataChartJson.map(entrada => [entrada.NomePais, entrada.Media, entrada.DesvioPadrao, entrada.Minimo, entrada.Maximo]);
            dataAsArray.unshift(['País', 'Média', 'Desvio Padrão', 'Mínimo', 'Máximo',]);

            var data = google.visualization.arrayToDataTable(dataAsArray);

            var options = {
                chart: {
                    title: 'Métricas de uso de energia per capita',
                    subtitle: 'Valor em Kg de óleo per capita',
                },
                bars: 'horizontal', // Required for Material Bar Charts.
                height: 600,
                width: 800
            };

            var chart = new google.charts.Bar(document.getElementById('chartMetricas'));
            chart.draw(data, google.charts.Bar.convertOptions(options));
        }

        //Recarregar com os novos dados
        function reloadChart(relatorioMetricas) {
            var dataAsArray = relatorioMetricas.map(entrada => [entrada.NomePais, entrada.Media, entrada.DesvioPadrao, entrada.Minimo, entrada.Maximo]);
            dataAsArray.unshift(['País', 'Média', 'Desvio Padrão', 'Mínimo', 'Máximo',]);

            console.log(relatorioMetricas);
            console.log(dataAsArray);

            var chartMetrics = new google.charts.Bar(document.getElementById('chartMetricas'))

            var chartMetricsData = google.visualization.arrayToDataTable(dataAsArray);

            var options = {
                chart: {
                    title: 'Métricas de uso de energia per capita',
                    subtitle: 'Valor em Kg de óleo per capita',
                },
                bars: 'horizontal', // Required for Material Bar Charts.
                height: 600,
                width: 800
            };

            chartMetrics.draw(chartMetricsData, google.charts.Bar.convertOptions(options));
        }
    </script>
}

DapperGraphs/Views/EnergyUsageDatas/GerarGraficoTop10.cshtml
@{
    ViewBag.Title = "Relatório Gráfico de Colunas";
}

<h2>Relatório Gráfico de Colunas</h2>

<div id="top_x_div"></div>

@section Scripts {
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $.ajax({
                type: 'POST',
                dataType: 'json',
                contentType: 'application/json',
                url: '@Url.Action("GerarDadosRelatorioTop10", "EnergyUsageDatas")',
                success: function (result) {
                    google.charts.load('current', { 'packages': ['bar'] });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });

        function drawChart(result) {
            var arrays = [
                result.map(value => value.Pais),
                result.map(value => value.Valor)
            ];

            arrays[0].splice(0, 0, ' ');
            arrays[1].splice(0, 0, ' ');

            var data = new google.visualization.arrayToDataTable(arrays);

            var options = {
                height: 800,
                legend: { position: 'none' },
                chart: {
                    title: 'Top 10 Países',
                    subtitle: 'Kg de óleo equivalente per capita'
                },
                axes: {
                    x: {
                        0: { side: 'top' } // Top x-axis.
                    }
                },
                bar: { groupWidth: "90%" }
            };

            var chart = new google.charts.Bar(document.getElementById('top_x_div'));
            chart.draw(data, google.charts.Bar.convertOptions(options));
        }
    </script>
}

DapperGraphs/Views/EnergyUsageDatas/GerarRelatorioAnalitico.cshtml
@model IEnumerable<DapperGraphs.Models.EnergyUsageData>

@{
    ViewBag.Title = "Relatório Analítico";
}

<h2>Relatório Analítico</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Country.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Year)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Value)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Country.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Year)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Value)
        </td>
    </tr>
}

</table>

DapperGraphs/Views/EnergyUsageDatas/RelatorioAnalitico.cshtml
@{
    ViewBag.Title = "Relatório Analítico";
}

<h2>Relatório Analítico</h2>

@using (Html.BeginForm("GerarRelatorioAnalitico", "EnergyUsageDatas", FormMethod.Get, new { @id = "formConsultar", @name = "formConsultar" }))
{
    <div class="form-group">
        <label for="Ano">Período de ano:</label>
        <input type="text" class="form-control" name="anoInicial" id="anoInicial" placeholder="de" maxlength="4">
        <input type="text" class="form-control" name="anoFinal" id="anoFinal" placeholder="até" maxlength="4">
    </div>

    <div class="form-group">
        <label for="Country">País</label>
        @Html.DropDownList("Paises", ViewBag.Paises as SelectList, new { @class = "form-control", @id = "pais" })
    </div>

    <button type="submit" class="btn btn-default">Consultar</button>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            //Validações do form
            $("#formConsultar").validate({ // initialize the plugin
                rules: {
                    anoInicial: {
                        required: true,
                        minlength: 4,
                        maxlenght: 4,
                        number: true
                    },
                    anoFinal: {
                        required: true,
                        minlength: 4,
                        maxlenght: 4,
                        number: true
                    },
                    Paises: {
                        required: true
                    }
                },
                messages: {
                    anoInicial: {
                        required: "Informe o ano inicial da consulta!",
                        minlength: "O ano deve ter 4 digítos!",
                        maxlenght: "O ano deve ter 4 digítos!",
                        number: "O ano deve conter apenas números!"
                    },
                    anoFinal: {
                        required: "Informe o ano final da consulta!",
                        minlength: "O ano deve ter 4 digítos!",
                        maxlenght: "O ano deve ter 4 digítos!",
                        number: "O ano deve conter apenas números!"
                    },
                    Paises: {
                        required: "Escolha um país!"
                    }
                }
            })
        });
    </script>
}

DapperGraphs/Views/EnergyUsageDatas/RelatorioAnaliticoMetricas.cshtml
@{
    ViewBag.Title = "Relatório Analítico de Métricas";
}

<h2>Relatório Analítico de Métricas</h2>

@using (Html.BeginForm("GerarRelatorioAnaliticoMetricas", "EnergyUsageDatas", FormMethod.Get, new { @id = "formConsultar", @name = "formConsultar" }))
{
    <div class="form-group">
        <label for="Ano">Período de ano:</label>
        <input type="text" class="form-control" name="anoInicial" id="anoInicial" placeholder="de" maxlength="4">
        <input type="text" class="form-control" name="anoFinal" id="anoFinal" placeholder="até" maxlength="4">
    </div>

    <button type="submit" class="btn btn-default">Consultar</button>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            //Validações do form
            $("#formConsultar").validate({ // initialize the plugin
                rules: {
                    anoInicial: {
                        required: true,
                        minlength: 4,
                        maxlenght: 4,
                        number: true
                    },
                    anoFinal: {
                        required: true,
                        minlength: 4,
                        maxlenght: 4,
                        number: true
                    }
                },
                messages: {
                    anoInicial: {
                        required: "Informe o ano inicial da consulta!",
                        minlength: "O ano deve ter 4 digítos!",
                        maxlenght: "O ano deve ter 4 digítos!",
                        number: "O ano deve conter apenas números!"
                    },
                    anoFinal: {
                        required: "Informe o ano final da consulta!",
                        minlength: "O ano deve ter 4 digítos!",
                        maxlenght: "O ano deve ter 4 digítos!",
                        number: "O ano deve conter apenas números!"
                    }
                } 
            })
        });
    </script>
}